### ISSUE TITLE
Ability to specify configuration via environment variables using docker

### ISSUE THREAD

**Issue by emilt27** [pryv/open-pryv.io#13]
I'm using docker-compose based Pryv installation, and it would be great to have the ability to specify some configuration via environment variables instead of mounting the config file. E.g:
```
services:
  open-pryv.io:
    image:  pryvio/open-pryv.io:latest
    command: "yarn api"
    container_name: "open-pryv.io"
    environment:
        DNSLESS_PUBLIC_URL:  http://localhost:3000
        AUTH_ADMIN_ACCESS_KEY:  CHANGE_ME
        AUTH_TRUSTED_APPS: "*@https://pryv.github.io, *@http://*localhost*"
        DATABASE_HOST: open-pryv-mongo
        DATABASE_PORT: 27017
        DATABASE_NAME: pryv-node
    ports:
        - 3000:3000
    depends_on:
        - open-pryv-mongo
    networks:
        - app-network
```

Is it possible?

**Comment by perki** [comment]
Hello @emilt27 

Yes it's.

configuration items can be changed from the command line. You can couple this with environment variables.

Exemple:

```
export SERVICE_NAME="My own Pryv"
yarn api --service.name=$SERVICE_NAME
```

**Comment by kebetsi** [comment]
Hi @emilt27,

We're building a new version where you will be able to provide config values with the same case, separated by `__` (double undeerscore), as environment variables in the following way:

```yaml
services:
  open-pryv.io:
    image:  pryvio/open-pryv.io:latest
    command: "yarn api"
    container_name: "open-pryv.io"
    environment:
        dnsLess__publicUrl:  http://localhost:3000
        auth__adminAccessKey:  CHANGE_ME
        auth__trustedApps: "*@https://pryv.github.io, *@http://*localhost*"
    ports:
        - 3000:3000
    depends_on:
        - open-pryv-mongo
    networks:
        - app-network
```

We'll let you know when it's ready later this afternoon.
