### ISSUE TITLE
Pryv docker cannot start

### ISSUE THREAD

**Issue by ovesco** [pryv/open-pryv.io#16]
I downloaded latest docker archive to run pryv in a local environment, edited the dockerized-config.yml file as stated in the readme, but the open-pryv.io container fails to start and enters an infinite restart loop. The following error is displayed:
```
open-pryv.io     |   value: {
open-pryv.io     |     adminAccessKey: 'REPLACE_ME',
open-pryv.io     |     trustedApps: '*@https://pryv.github.io, *@https://*.rec.la*'
open-pryv.io     |   },
open-pryv.io     |   scope: 'base',
open-pryv.io     |   info: 'From file: ./config.json'
open-pryv.io     | }
```

But the file was correctly modified and I set another value for `adminAccessKey`.

**Comment by perki** [comment]
Hello, 
It seems another config file is used. 
How do you launch open-pryv ? 
With: `docker-compose -f production-with-ssl/docker-compose.yml up` ?

**Comment by ovesco** [comment]
No I used the one defined in the readme: `docker-compose -f local/docker-compose.with-ssl.yml up` after editing the `local/dockerized-config.yml`

**Comment by perki** [comment]
Then only `docker-compose.with-ssl.yml` is used and not `dockerized-config.yml` 
You should edit the "ssl" one if you use it

**Comment by ovesco** [comment]
But the `docker-compose.with-ssl.yml` file states that for open-pryv.io:
```yml
open-pryv.io:
  # [...]
  volumes:
    - ./dockerized-config.yml:/app/config.yml
```
The dockerized-config.yml file is used in the image, there is no REPLACE_ME in the dockerfile itself

**Comment by kebetsi** [comment]
Hi @ovesco,

As stated by the README:

--------------------

## Local dev with SSL

1. Edit the following value in the [Config](https://github.com/pryv/open-pryv.io#config) file `local/dockerized-config.yml`:
   - auth:adminAccessKey: secret for admin functions, change it from its default value otherwise Open Pryv.io will crash on boot.

2. Run:

```bash
docker-compose -f local/docker-compose.with-ssl.yml up
```
------------------------

You have edited the `local/dockerized-config.yml` file, changing the `auth:adminAccessKey` property from its default `REPLACE_ME` value.
Then you have run `docker-compose -f local/docker-compose.with-ssl.yml up`.
Is this correct?

Can you post us an extract of `local/dockerized-config.yml` and print more logs from when you run it?

Best,
Ilia

**Comment by ovesco** [comment]
Hi,

This is the content of my local/dockerized-config.yml file:
```yml
openSource:
  isActive: true
dnsLess:
  isActive: true
  publicUrl: https://my-computer.rec.la:4443
http:
  port: 3000
  ip: 0.0.0.0
auth:
  adminAccessKey: VerySecureMuchKey2021
  trustedApps: "*@https://pryv.github.io, *@https://*.rec.la*, *@https://*.yo.yo"
eventFiles:
  attachmentsDirPath: "/app/data/attachments"
service:
  name: Open-Pryv.io
  support: https://pryv.com/open-pryv-non-configured-page/
  terms: https://pryv.com/open-pryv-non-configured-page/
  home: https://pryv.com/open-pryv-non-configured-page/
  eventTypes: https://api.pryv.com/event-types/flat.json
services:
  email:
    enabled:
      welcome: true
      resetPassword: true
    url: http://open-pryv-mail:9000/sendmail/
database:
  host: open-pryv-mongo
```

Note that I added the `@https://*.yo.yo` to see if it appeared in docker logs output, but it does not:
```
Container open-pryv-mongo  Created
Container open-pryv.io  Created
Container open-pryv-mail  Created
Container open-pryv-nginx  Created
Attaching to open-pryv-mail, open-pryv-mongo, open-pryv-nginx, open-pryv.io
open-pryv-mongo  | 2021-11-28T16:02:16.393+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
open-pryv-mongo  | 2021-11-28T16:02:16.395+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=a771231a03e2
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten] db version v4.2.9
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten] git version: 06402114114ffc5146fd4b55402c96f1dc9ec4b5
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten] modules: none
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten] build environment:
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten]     distarch: x86_64
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
open-pryv-mongo  | 2021-11-28T16:02:16.396+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
open-pryv-mongo  | 2021-11-28T16:02:16.399+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
open-pryv-mongo  | 2021-11-28T16:02:16.401+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=12273M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
open-pryv.io     | yarn run v1.22.5
open-pryv.io     | $ NODE_ENV=production ./dist/components/api-server/bin/server --config ./config.json
open-pryv.io     | 2021-11-28 16:02:17 [warn]: [api-server:config]: Null or Undefined Url for [serviceInfo]
open-pryv.io     | 2021-11-28 16:02:17 [error]: [api-server:validate-config]: Configuration is invalid at [auth:adminAccessKey] field content should be replaced {
open-pryv.io     |   value: {
open-pryv.io     |     adminAccessKey: 'REPLACE_ME',
open-pryv.io     |     trustedApps: '*@https://pryv.github.io, *@https://*.rec.la*'
open-pryv.io     |   },
open-pryv.io     |   scope: 'base',
open-pryv.io     |   info: 'From file: ./config.json'
open-pryv.io     | }
open-pryv.io     | error Command failed with exit code 1.
open-pryv.io     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
open-pryv.io exited with code 1
```
