### ISSUE TITLE
Error setting up Pryv with FerretDB

### ISSUE THREAD

**Issue by orla-ske** [pryv/open-pryv.io#23]
I encountered an error when trying to set up Pryv using FerretDB as the database. I followed the instructions [here](https://github.com/pryv/open-pryv.io/tree/master/ferretDB) and encountered this error 
```
2024-07-16 14:31:03 [error]: [api-server:serverRoot] MongoServerError: Received authentication for mechanism PLAIN which is not enabled MongoServerError: Received authentication for mechanism PLAIN which is not enabled
    at Connection.onMessage (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-master/node_modules/mongodb/lib/cmap/connection.js:231:30)
    at MessageStream.<anonymous> (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-master/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-master/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-master/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:809:22)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 334,
  codeName: 'MechanismUnavailable',
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}
```
Any help will be appreciated. 
Orlando.

**Comment by perki** [comment]
Hi Orlando, 

I just made a test on a new open-pryv checkout 

What I did, was 

- `npm run setup-dev-env`

- `npm install`

- edited configs/api.yml 

  - changed adminAccessKey

  - added 

    ```
    database: 
      isFerretDB: true 
      authUser: ...
      authPassword: ...
       
    ```

- run `npm api`  to create base `var-pryv`file structure (maybe this is a step missing in the doc) 
  - Then stop api  
- go to ferretDB folder 
  - edit `docker-compose.yml`  and set correct password and username 
  - run `docker compose up -d`
  - run `docker run --rm -it --network=ferretdb --entrypoint=mongosh mongo "mongodb://{usrename}:{password}@ferretdb/ferretdb?authMechanism=PLAIN"
- go back to main folder 
- run `npm run api`

And everything went fine. 

Could you confirm that you followed the same steps ?

An important point about ferretDB performance, the following are execution times of the test suite:
- standard (mongo + sqlite) : 4m30
- fullMongo : 4m58
- ferretDB (dans un container docker) : 28m30
- sqlite+ (only events, mongo is still used streams et access) :  2m53

As you can see Pryv's tests on ferretDB are about 6x slower than with mongoDB. I’m not sure it’s a good choice for production unless you want to use only full open-source stack. 
If you really want to use Postgres, it might be more efficient to write a PostreSQL implementation based on the SQLite one as the semantic are very close.

**Comment by orla-ske** [comment]
Upon following the above instructions, i am still encountering an error slightly different from the previously mentioned: 

```
2024-07-18 15:48:56 [error]: [api-server:serverRoot] MongoServerError: Unsupported authentication mechanism "SCRAM-SHA-1".
See https://docs.ferretdb.io/security/authentication/ for more details. MongoServerError: Unsupported authentication mechanism "SCRAM-SHA-1".
See https://docs.ferretdb.io/security/authentication/ for more details.
    at Connection.onMessage (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-ferretDB/node_modules/mongodb/lib/cmap/connection.js:231:30)
    at MessageStream.<anonymous> (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-ferretDB/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-ferretDB/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-ferretDB/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:809:22)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 18,
  codeName: 'AuthenticationFailed',
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}
```

**Comment by perki** [comment]
Hello Orlando, 

There might be a difference due to ferretDB latest release. 

Can you add `:1.21.0` to force the version of ferretDB to the file `ferretDB/docker-compose.yml` ?

```
ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1.21.0
```

Best regards, 
Pierre-Mikael

**Comment by orla-ske** [comment]
Still running into the same error:

```
2024-07-19 20:34:27 [error]: [api-server:serverRoot] MongoServerError: SCRAM authentication is not enabled MongoServerError: SCRAM authentication is not enabled
    at Connection.onMessage (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-ferretDB/node_modules/mongodb/lib/cmap/connection.js:231:30)
    at MessageStream.<anonymous> (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-ferretDB/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-ferretDB/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/Users/orlandokodjo/Downloads/PROFILA/demo/open-pryv.io-ferretDB/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:809:22)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 18,
  codeName: 'AuthenticationFailed',
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}
```
Could it be because I am using a Mac environment? However taking you advice from above i believe I will rite a PostgreSQL implementation using the SQLite schema. I however would like to complete the setup with ferretDB.
Thanks Again.

**Comment by perki** [comment]
Hello Orlando,

This error is typical of the following situation: 
1- ferretDb is correctly started 
2- configuration is still pointing to mongodb implementation

Could you please share your `config/api.yml` config file? (change secrets `adminAccessKey` and `database:authPassword`) 

Kind regards,

**Comment by orla-ske** [comment]
Hello Pierre-Mikael, 
Kindly find it below: 

```
dnsLess:
  publicUrl: http://localhost:3000/ # the "Public" URL to reach the service, you need to change this if you use a third party SSL service such as NGNIX.
http:
  port: 3000 # (ignored with docker) The local port to listen
  ip: 127.0.0.1 # (ignored with docker) The IP adress to use. Keep it 127.0.0.1 unless you explicitely want to expose the service in `http` to another network.
  ssl:
    keyFile: false # to enable HTTPS give the full path to your SSL key file in pem format
    certFile: false # to enable HTTPS give the full path to your SSL certificate file in pem format
    caFile: false # (optional) full path to your SSL certificate-authority file in pem format
auth:
  adminAccessKey: {access key} # key to use for system calls such as `/reg/admin/users`. A random key should be generated on setup.
  trustedApps: "*@https://pryv.github.io*, *@https://*.rec.la*, *@https://*.backloop.dev*" # list of web apps that can be trusted-app functionalities
database: 
  isFerretDB: true 
  authUser: {username}
  authPassword: {password}
service:
  serial: 1000001 # change serial number each time assets content needs to be reloaded by clients
  name: Open-Pryv.io
  support: https://pryv.com/open-pryv-non-configured-page/
  terms: https://pryv.com/open-pryv-non-configured-page/
  home: https://pryv.com/open-pryv-non-configured-page/
  eventTypes: https://pryv.github.io/event-types/flat.json
services:
  email:
    enabled:
      welcome: true
      resetPassword: true
custom:
  systemStreams:
    account:
      -
        isIndexed: true
        isUnique: true
        isShown: true
        isEditable: true
        type: email/string
        name: Email
        id: email
        isRequiredInValidation: true
```
